version: "2.0"
services:
  web:
    container_name: magento2-docker
    image: tecrahul/magento2-docker
    ports:
       - "8085:80"
       - "1443:443"
       - "2202:22"
    volumes:
      - ./html:/var/www/html
    restart: always
  mysql_db:
    image: mysql:5.6
    container_name: magento2_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: magento2_docker
      MYSQL_USER: magento2_docker
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: pass123
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8086:80
    volumes:
     - /sessions
